# Generated by Django 3.2.8 on 2021-10-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_game_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ascension_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_floor',
            field=models.IntegerField(),
        ),
    ]
