# Generated by Django 4.1 on 2022-08-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_auto_20211011_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='version',
            field=models.IntegerField(),
        ),
    ]
